export const theme = {
  colors: {
    dark: {
      surfacePrimary: '#222220',
      surfaceSecondary: '#2A2A28',
      surfaceTertiary: '#333331',
      textPrimary: '#F3F3F1',
      textSecondary: '#A8A8A4',
      textMuted: '#747470',
      accent: '#4A6FA3',
      accentHover: '#5A7FB3',
      border: '#3A3A38',
      userBubble: '#2E3D50',
      agentBubble: '#2A2A28',
    },
    light: {
      surfacePrimary: '#F8F8F7',
      surfaceSecondary: '#FFFFFF',
      surfaceTertiary: '#F0F0EE',
      textPrimary: '#2A2A28',
      textSecondary: '#5A5A56',
      textMuted: '#8A8A86',
      accent: '#3B5F8C',
      accentHover: '#4A6FA3',
      border: '#E0E0DC',
      userBubble: '#3B5F8C',
      agentBubble: '#F0F0EE',
    },
  },
  status: {
    online: '#1E8E3E',
    busy: '#E8AB02',
    offline: '#C41C1C',
    idle: '#747470',
  },
  radii: {
    card: '12px',
    button: '8px',
    input: '6px',
  },
  fonts: {
    sans: "'Inter', system-ui, -apple-system, sans-serif",
    mono: "'JetBrains Mono', ui-monospace, monospace",
  },
} as const
